### ISSUE TITLE
Issue installing the tool

### ISSUE THREAD

**Issue by paultown99** [svrooij/WingetIntune#10]
### Command

install

### Full command

dotnet tool install --global SvRooij.Winget-Intune.Cli

### App version

Latest Published

### What happened?

Install fails:-

### Relevant log output

```Shell
PS C:\Program Files\WindowsPowerShell\Scripts> dotnet tool install --global Winget-Intune.Cli
C:\Users\user\AppData\Local\Temp\b7b7aab7-2de5-491a-b447-3c9539bb60ca\restore.csproj : error NU1101: Unable to find pa
ckage winget-intune.cli. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
The tool package could not be restored.
Tool 'winget-intune.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@paultown99 can you verify that it works if you added the nuget source, like describe in [this](https://stackoverflow.com/a/73961223/639153] answer?

Adding the nuget source seems to be something that is done if you install visual studio, but not if you just install dotnet.

**Comment by paultown99** [comment]
It's working nowl
