### ISSUE TITLE
[Bug]: RoleScopeTags not being applied

### ISSUE THREAD

**Issue by w0** [svrooij/WingetIntune#114]
### CommandLet

Deploy-WtWin32App

### Full command

 New-WtWingetPackage -PackageId "Neovim.Neovim" -PackageFolder C:\Packages | Deploy-WtWin32App -RoleScopeTags '5','9'

### Module version

1.0.2

### What happened?

The RoleScopeTags 5 and 9 are not applied when the application is uploaded. It just has the default tag. 
[win32LobApp.json](https://github.com/user-attachments/files/16855737/win32LobApp.json)

### Command output

```PowerShell
INFO: Loading package details from folder C:\Packages\Neovim.Neovim\0.10.1
INFO: Adding role scope tags to app
INFO: Uploading Win32App Neovim to Intune with file C:\Packages\Neovim.Neovim\0.10.1\nvim-win64.intunewin

Owner                           :
PrivacyInformationUrl           :
Publisher                       : neovim.io
PublishingState                 : Published
Relationships                   :
RoleScopeTagIds                 : {0}
SupersededAppCount              : 0
SupersedingAppCount             : 0
UploadState                     : 1
```

### PowerShell version

7.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
You can use that as a temporary fix then. And then we can fix the parameter in the code some time soon.
