### ISSUE TITLE
[Bug]: PowerShell ..."A circular dependency was created while adding app relationships."

### ISSUE THREAD

**Issue by iannels** [svrooij/WingetIntune#125]
### CommandLet

Remove-WtWin32App

### Full command

Remove-WtWin32App -AppId "513ad74a-05ba-4723-b72e-30460e495b5d"

### Module version

0.9.1

### What happened?

I tried to remove an app that was superseded and got the following error when attempting to update the app relationship

### Command output

```PowerShell
INFO: Removing app 513ad74a-05ba-4723-b72e-30460e495b5d from Intune
INFO: Updating relations of app 1dee514f-bdef-45d3-8dde-ff4e7c65d5de to remove 513ad74a-05ba-4723-b72e-30460e495b5d
Remove-WtWin32App: {
  "_version": 3,
  "Message": "A circular dependency was created while adding app relationships. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: f0df7308-ab86-44e1-8819-114aff698275 - Url: https://fef.amsua0102.manage.microsoft.com/AppLifecycle_2409/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('1dee514f-bdef-45d3-8dde-ff4e7c65d5de')/microsoft.management.services.api.updateRelationships?api-version=5024-06-25",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
```

### PowerShell version

7.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Someone already noticed this issue, and it is fixed in this PR
https://github.com/svrooij/WingetIntune/pull/118

But I've not created a release just yet. Will do that soon
