### ISSUE TITLE
[Bug]: PowerShell SupersededApp - copy of assignments not working

### ISSUE THREAD

**Issue by NiklasPuschData** [svrooij/WingetIntune#127]
### CommandLet

Deploy-WtWin32App

### Full command

Deploy-WtWin32App -GraphId "old-graph-id" -RootPackageFolder "path-to-root" -PackageId "packageid" -Version "version"

### Module version

1.0.2

### What happened?

**Expected Behavior**
All specified data (assignments, tags, and other relevant information) should be successfully transferred to the new app when the command is executed.

**Actual Behavior**
The data is not being transferred to the new app. The new app is not receiving the expected information.

### PowerShell version

7.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@NiklasPuschData I think this issue was solved in version [1.0.3](https://github.com/svrooij/WingetIntune/discussions/133), can you verify and otherwise re-open this issue?
