### ISSUE TITLE
[Bug]: CLI ... MSAL authentication error

### ISSUE THREAD

**Issue by granwalla** [svrooij/WingetIntune#129]
### Command

publish

### Full command

wintuner publish Zoom.Zoom --package-folder "C:\Scripts\Winget-Packages"

### App version

0.9.1+6c877cd1e0c885ac2d42f4a8243e0e35b8fb4662

### What happened?

I was able to create a package with no issue, but I can't publish it. When I run the command, one of three things happens.

1. I get an error "MSAL.NetCore.4.62.0.0.MsalClientException: ErrorCode: authentication_canceled Microsoft.Identity.Client.MsalClientException: User canceled authentication." My PS session completely locks up and I have to close with Task Manager.

2.  I get an error "MSAL.NetCore.4.62.0.0.MsalClientException: ErrorCode: authentication_canceled Microsoft.Identity.Client.MsalClientException: User canceled authentication." An auth pop-up come on, but it's not the standard one I'm used to seeing. I can't login to it, my PS session completely locks up, and I have to close with Task Manager.

3.  I get an error "MSAL.NetCore.4.62.0.0.MsalClientException: ErrorCode: authentication_canceled Microsoft.Identity.Client.MsalClientException: User canceled authentication." My PS session does not lock up, but it also hasn't asked for authentication.

If you have any ideas, please advise. Thank you.

### Windows version and current language

Windows 11 English

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
I would say try the Powershell module instead. It works much better.

The dotnet cli is going away soon.

**Comment by granwalla** [comment]
Darn, I was enjoying the CLI stuff since it's new to me. :) But thanks for the quick reply, I'll stick with PowerShell.

**Comment by svrooij** [comment]
> Darn, I was enjoying the CLI stuff since it's new to me. :) But thanks for the quick reply, I'll stick with PowerShell.

I feel the same, but most people using it are not developers and don't have dotnet sdk installed. So PowerShell module is the way forward. It is calling mostly the same code anyway

**Comment by granwalla** [comment]
Hi, me again. I've installed the WinTuner module, but I can't get past authentication.

PS C:\Windows\System32> Connect-WtWinTuner -Username "sarah@contoso.com"

_Connect-WtWinTuner: The term 'Connect-WtWinTuner' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

In the module folder, I noticed the WinTuner.psm1 file is empty, is that normal?

**Comment by granwalla** [comment]
OK, that seemed to work. I used the same Connect-WtWinTuner command as above and it gives me:

_INFO: Connecting to Intune using Interactive_

Nothing prompts for my password.

**Comment by ontech704** [comment]
Same issue, nothing prompts after I get the INFO: Connecting to Intune using Interactive

**Comment by Cat-Snack-Jack** [comment]
What works for me - 
Install-Module WinTuner
Import-Module WinTuner
Connect-WtWinTuner user@domain.onmicrosoft.com 
Connect-WtWinTuner user@domain.onmicrosoft.com -test
 - Accept Consent Prompt

Also -
Be sure you're in Powershell 7, if not install it and run the correct powershell
winget install Microsoftr.Powershell

**Comment by ontech704** [comment]
I’ve tried that running PowerShell 7.4.6 and still just get the following after the prompt. Nothing comes up.

INFO: Connecting to Intune using Interactive


From: Cat-Snack-Jack ***@***.***>
Date: Sunday, October 27, 2024 at 2:14 PM
To: svrooij/WingetIntune ***@***.***>
Cc: Jon Helm ***@***.***>, Comment ***@***.***>
Subject: Re: [svrooij/WingetIntune] [Bug]: CLI ... MSAL authentication error (Issue #129)

What works for me -
Install-Module WinTuner
Import-Module WinTuner
Connect-WtWinTuner ***@***.******@***.***>
Connect-WtWinTuner ***@***.******@***.***> -test

  *   Accept Consent Prompt

Also -
Be sure you're in Powershell 7, if not install it and run the correct powershell
winget install Microsoftr.Powershell

**Comment by svrooij** [comment]
Try using this command, `Connect-WtWinTuner -Username user@domain.onmicrosoft.com -test`

It will try to get a token immediately (which will also cache the token)

Otherwise try with the `-NoBroker` switch, it will just use the default browser to get a token.

Last resort:

1. Install the Azure CLI
2. Login to the Azure CLI in whatever way you like
3. Run `Connect-WTWinTuner -UseDefaultCredentials -Test`

This will use the login logic of the cli instead

**Comment by svrooij** [comment]
If you're still having this issue you can re-open the issue.

**Comment by ontech704** [comment]
When I run the command **Connect-WTWinTuner -UseDefaultCredentials -Test**, it pops up the login box. 

Once I take the -Test off, I get the same message: **INFO: Connecting to Intune using Interactive** and nothing ever comes up.

![Screenshot 2024-11-13 203240](https://github.com/user-attachments/assets/80d35841-d03d-4e8d-a70d-a611dbbbd3b5)

**Comment by svrooij** [comment]
And then it will authenticate the first time it needs a token. Maybe I'm just going to remove the test parameter and make that default.

It is super frustrating that all the issues are about authentication, while that uses a Microsoft library that should make things easier.
