### ISSUE TITLE
[Bug]: Error code when trying to run 'package'

### ISSUE THREAD

**Issue by billybenson** [svrooij/WingetIntune#13]
### Command

package

### Full command

 winget-intune.exe package google.chrome --source winget --package-folder C:\Tools  

### App version

 0.5.0+Branch.main.Sha.21e3133b7f0b943661dc671ed22f4be9093e0b86 

### What happened?

Hi - thanks for the tool. I am just testing and I am receiving an error when running the command to package Google Chrome.

Error message:

 PS C:\Windows\system32> winget-intune package google.chrome --source winget --package-folder C:\Tools
info: WingetIntune.Implementations.WingetManager[4] Getting package info for google.chrome (null)
warn: WingetIntune.Os.ProcessManager[3] Process exited with code -1978335212. 
warn: WingetIntune.Implementations.WingetManager[100] Error getting package info for google.chrome (null):  System.Exception: Winget exited with non-zero exitcode
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@billybenson the `packageId` in the command is case sensitive. You should try with `Google.Chrome`. But I also found (and fixed) a bug that kept it from parsing the manifest. So you should [update](https://github.com/svrooij/WingetIntune#installing)

**Comment by billybenson** [comment]
Thanks - this is all working now.
I have just tested a second app - and this is also failing. I will create a new Issue.
Thanks.
