### ISSUE TITLE
[Bug]: PowerShell ...

### ISSUE THREAD

**Issue by Apmoek** [svrooij/WingetIntune#131]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageID Microsoft.PowerToys -PackageFolder C:\Temp

### Module version

1.0.2

### What happened?

The command completed with an error, I checked the output location and see that I have a detection script and a intune.win package. I will paste the error under here, I am curious if this should happen automatically or that I should have done something. 

### Command output

```PowerShell
New-WtWingetPackage: Could not find file 'C:\Temp\Microsoft.PowerToys\logo.png'.
```

### PowerShell version

7.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Duplicated of #120
