### ISSUE TITLE
[Bug]: PowerShell ...

### ISSUE THREAD

**Issue by Apmoek** [svrooij/WingetIntune#134]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageID Skillbrains.Lightshot -PackageFolder C:\Temp

### Module version

1.0.2

### What happened?

I tried packaging Lightshot, but I got a forbidden reply. 

### Command output

```PowerShell
INFO: Packaging package Skillbrains.Lightshot 5.5.0.7
INFO: [WingetManager] Getting package info for Skillbrains.Lightshot 5.5.0.7 from github
INFO: [IntuneManager] Generating IntuneWin package for Skillbrains.Lightshot 5.5.0.7 X86 System in C:\Temp
INFO: [IntuneManager] Downloading installer from http://updater.prntscr.com/builds/setup-lightshot-5.5.0.7.exe to C:\Users\jvanderhorst\AppData\Local\Temp\wintuner\Skillbrains.Lightshot\5.5.0.7\setup-lightshot-5.5.0.7.exe
INFO: [DefaultFileManager] Downloading http://updater.prntscr.com/builds/setup-lightshot-5.5.0.7.exe to C:\Users\jvanderhorst\AppData\Local\Temp\wintuner\Skillbrains.Lightshot\5.5.0.7\setup-lightshot-5.5.0.7.exe
New-WtWingetPackage: Response status code does not indicate success: 403 (Forbidden).
```

### PowerShell version

7.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
The server where you're downloading it from does not like the user agent (or is broken) nothing I can do to help.
