### ISSUE TITLE
[Bug]: PowerShell Update-WtIntuneApp doest not accept $true argument. 

### ISSUE THREAD

**Issue by besirsoz** [svrooij/WingetIntune#135]
### CommandLet

other

### Full command

Update-WtIntuneApp -AppId xxxxxxxxxxxxxxxxxxxxxx -EnableAutoUpdate $true

### Module version

1.0.3

### What happened?

Trying to set up auto-update for an application I have deployed. But the argument is not getting accepted. 

### Command output

```PowerShell
Update-WtIntuneApp: A positional parameter cannot be found that accepts argument 'True'
```

### PowerShell version

7.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
I think all commands were converted to `SwitchParameters` meaning it is true if you add `-EnableAutoUpdate` and false if you don't.

Maybe it's missing this in the docs? Where did you find that info?
