### ISSUE TITLE
[Bug]: PowerShell ...New-WtWingetPackage ignores InstallerArguments for MSI installer

### ISSUE THREAD

**Issue by mdurini-swisscom** [svrooij/WingetIntune#137]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageId "Romanitho.Winget-AutoUpdate" -PackageFolder "XXXXXXXXXXXX\Various\WintunerPackages\" -InstallerArguments "/qn RUN_WAU=YES USERCONTEXT=1 STARTMENUSHORTCUT=1 NOTIFICATIONLEVEL=SuccessOnly UPDATESINTERVAL=Daily"

### Module version

1.0.3

### What happened?

Hi, it seems that the app is packaged locally ignoring the installer arguments. There are no errors in powershell console, but parameters are not showed in the json and in Intune

### PowerShell version

7.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
It seems the `-InstallerArguments` are ignored for msi installers, will fix this soon
