### ISSUE TITLE
[Bug]: PowerShell Git Install doesn't detect properly

### ISSUE THREAD

**Issue by crcobb** [svrooij/WingetIntune#142]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageId "Git.Git" -PackageFolder $rootPackageFolder -Verbose -Debug

### Module version

1.0.3

### What happened?

Package was created properly and Git.Git was installed.  The issue occurs with the detection logic.

The logic that maps the installs in ARP to winget packages considers Git to be ambiguous.  Both Git.Git and Microsoft.Git have a name of Git and the mapping logic can't decide which is correct so it doesn't map any winget packages to the Git install.

If you install via command winget install Git.Git it does the mapping properly.  It appears that some additional data is stored per user in SQLite DB to help winget know which version you installed.

Not sure if there is fix for this issue.  Maybe some type of change to the detection logic, just not seeing any get solution to changing that logic.  Maybe something that doesn't rely on winget? 

### PowerShell version

7.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
There also is an issue with apps that report the wrong Msi product code in the Winget repository.

Have considered making an install.ps1 for each app that installers the app with the needed parameters and then adds something wintuner tagged to the registry, but did not get into making that.

What do you propose? Any good ideas?

**Comment by crcobb** [comment]
Stephen,
Sorry I'm traveling this week and have intermittent access to the Internet.

I was looking at the logs generated when running the winget list -e git.git
(I think that is the correct syntax) as both a user and as the system
account.  You can see where it is strong the data and a reference to
Sqlite.

If you install Git using winget as a use you can see the difference in the
results of the winget list and the difference in the logs.

I believe you can quickly get to the logs with a the command winget  --logs
and an explorer window will be open to the correct folder.

**Comment by svrooij** [comment]
In case this happens, you should just try to use `-Packagescript` when creating the package. https://wintuner.app/docs/wintuner-powershell/New-WtWingetPackage

This will effectively create a script that just executes `winget install …`

**Comment by crcobb** [comment]
That worked perfectly.  I packaged an older version and then allowed it to update to a new version.  I'll keep thinking about other ideas to allow the installer to reside in Intune and detection to work properly.
