### ISSUE TITLE
[Bug]: Allow specify which installer you want (issue with AnyDeskSoftwareGmbH.AnyDesk)

### ISSUE THREAD

**Issue by mdurini-swisscom** [svrooij/WingetIntune#144]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageId "AnyDeskSoftwareGmbH.AnyDesk" -PackageFolder "xxxxx\" | Deploy-WtWin32App

### Module version

1.0.3

### What happened?

Hello, I saw that the command is supposed to generate the package for Anydesk 9.0, but i got packaged Anydesk MSI 8.1.0. The funny thing is that trying to run the command 
`winget install --id=AnyDeskSoftwareGmbH.AnyDesk  -e `
in a test machine, i got installed the Anydek 9.0

### PowerShell version

7.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
This might be bad timing.

WinTuner uses a public (by me) generated index of all packages. This index is refreshed every 6 hours directly from Winget.
Anydesk is updated 2 days ago

https://github.com/svrooij/winget-pkgs-index/blame/c1bead51d4b557b8b1a258a0fdcd8e28aed6182b/index.csv#L317

Your computer might also have a cached version of this file. Not sure what I put in as default cache time.

Winget repo update -> Winget index distributed -> each 6 hours, [winget index](https://wintuner.app/docs/related/winget-package-index) update.


this is only relevant if you don’t specify a version `-Version “9.0.0”`, would package your wanted version. Maybe this process should be documented better, any ideas?

**Comment by mdurini-swisscom** [comment]
I checked the local json file

![image](https://github.com/user-attachments/assets/0ea0140f-854a-4ffb-8ea6-bcf69cca77b2)

as you can see it's mentioned 9.0 as version but the package is the msi one, that is related to a different version

![image](https://github.com/user-attachments/assets/9ed1c54c-4908-4bbc-b0ad-1f9a9bbe6ac2)

the yaml file related to anydesk (microsoft repo) is pointing to the exe one
`https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AnyDeskSoftwareGmbH/AnyDesk/9.0.0/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml`

anyway, i remember the other issue that i opened, i guess that anydesk is one of the ISV that avoid to keep the correct versioning for the installers

**Comment by svrooij** [comment]
You could update the json before uploading, but that is not a real solution.

When running WinTuner in debug mode, I see that for the MSI they only specify the product code. Meaning the MsiVersion is not filled in so WinTuner loads it from the MSI itself, where it is set to `8.1.0`. 

![image](https://github.com/user-attachments/assets/2a3cc4c9-e5be-43fb-a2aa-54ed0ba973e3)

Would you suggest as a solution? Maybe create a parameter like `-UsePackageVersion` or `-OverrideDetectionVersion "9.0.0"`

**Comment by mdurini-swisscom** [comment]
i don't get one point...why wintuner (which uses winget) download the MSI file once in the yaml file what is used by winget it's mentioned the exe file with a different installation string?

**Comment by svrooij** [comment]
It prefers msi over exe. If it has an msi, it will just use that. So this [MSI](https://github.com/microsoft/winget-pkgs/blob/dd5f63532895d7db0bde9db600042a20c0e2f9c0/manifests/a/AnyDeskSoftwareGmbH/AnyDesk/9.0.0/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml#L28-L36) seems to be the old 8.1.0 version.
Specified in the 9.0.0 version package.

And because they also seem to re-use urls for installers (which is rather stupid if you ask me), there are no older versions available (they are probably removed because of a hash mismatch)

**Comment by mdurini-swisscom** [comment]
And now i got it :-) i didn't saw in the yaml that both files were mentioned. i got your point now....can you please an argument to define the InstallerType to download?

**Comment by svrooij** [comment]
Something like:

```plain
 new-wtWingetPackage -PackageId AnyDeskSoftwareGmbH.AnyDesk -PackageFolder D:\packages\ -PreferedInstaller Exe
INFO: Packaging package AnyDeskSoftwareGmbH.AnyDesk 9.0.0
INFO: [WingetManager] Getting package info for AnyDeskSoftwareGmbH.AnyDesk 9.0.0 from github
INFO: [ComputeBestInstallerForPackageCommand] Computing best installer for AnyDeskSoftwareGmbH.AnyDesk 9.0.0 Unknown
INFO: [IntuneManager] Generating IntuneWin package for AnyDeskSoftwareGmbH.AnyDesk 9.0.0 X86 System in D:\packages\
INFO: [IntuneManager] Downloading installer from https://download.anydesk.com/AnyDesk.exe to ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0\AnyDesk.exe
INFO: [DefaultFileManager] Downloading https://download.anydesk.com/AnyDesk.exe to ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0\AnyDesk.exe
INFO: [DefaultFileManager] Downloaded file https://download.anydesk.com/AnyDesk.exe has hash 'DC23F664BB17B89219D86433BD997202182C4BC178F39E78533244BE02AA7753' as expected
INFO: [Packager] Creating Intune package from ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0
INFO: [Packager] Creating package for ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0\AnyDesk.exe in ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0 to D:\packages\AnyDeskSoftwareGmbH.AnyDesk\9.0.0
INFO: [Packager] Compressing the source folder ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0 to ....AppData\Local\Temp\e8e784f6-530e-47fe-864c-5d2fdb467934\IntuneWinPackage\Contents\IntunePackage.intunewin
INFO: [Packager] Generating application info
INFO: [Packager] Encrypting file ....AppData\Local\Temp\e8e784f6-530e-47fe-864c-5d2fdb467934\IntuneWinPackage\Contents\IntunePackage.intunewin
INFO: [Packager] Generated detection XML file ....AppData\Local\Temp\e8e784f6-530e-47fe-864c-5d2fdb467934\IntuneWinPackage\Metadata\Detection.xml
INFO: [Packager] Done creating package for ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0\AnyDesk.exe in ....AppData\Local\Temp\wintuner\AnyDeskSoftwareGmbH.AnyDesk\9.0.0 to D:\packages\AnyDeskSoftwareGmbH.AnyDesk\9.0.0
INFO: [IntuneManager] Downloading logo from https://api.winstall.app/icons/AnyDeskSoftwareGmbH.AnyDesk.png
INFO: [DefaultFileManager] Skipping download of https://api.winstall.app/icons/AnyDeskSoftwareGmbH.AnyDesk.png to D:\packages\AnyDeskSoftwareGmbH.AnyDesk\logo.png because the file already exists
INFO: [IntuneManager] Writing detection info with msi details AnyDeskSoftwareGmbH.AnyDesk AnyDesk
INFO: [IntuneManager] Writing package readme for package AnyDeskSoftwareGmbH.AnyDesk

PackageId          : AnyDeskSoftwareGmbH.AnyDesk
Version            : 9.0.0
PackageFolder      : D:\packages\AnyDeskSoftwareGmbH.AnyDesk\9.0.0
PackageFile        : AnyDesk.intunewin
InstallerFile      : AnyDesk.exe
InstallerArguments : --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
                     --silent
```

**Comment by mdurini-swisscom** [comment]
yes, something like that will be perfect

**Comment by svrooij** [comment]
This fix will roll-out with the next update.
