### ISSUE TITLE
[Bug]: Cannot package app 

### ISSUE THREAD

**Issue by billybenson** [svrooij/WingetIntune#15]
### Command

package

### Full command

 winget-intune package Teamviewer.Teamviewer --package-folder c:\packages 

### App version

 0.5.1+Branch.main.Sha.4e664f91572820bcb6b450bc5e155110b24bfa79 

### What happened?

A bug happened! When installing winget app with ID Teamviewer.Teamviewer:

 PS C:\Windows\system32> winget-intune package Teamviewer.Teamviewer --package-folder c:\packages
info: WingetIntune.Implementations.WingetManager[4] Getting package info for Teamviewer.Teamviewer (null)
warn: WingetIntune.Os.ProcessManager[3] Process exited with code -1978335212. 
warn: WingetIntune.Implementations.WingetManager[100] Error getting package info for Teamviewer.Teamviewer (null):  System.Exception: Winget exited with non-zero exitcode
winget-intune : Unhandled exception: System.Exception: Winget exited with non-zero exitcode 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
I guess it's an outage on winget or something....

```Shell
winget-intune package TeamViewer.TeamViewer --package-folder C:\Tools\packages\
info: WingetIntune.Implementations.WingetManager[4] Getting package info for TeamViewer.TeamViewer (null)
info: WingetIntune.Commands.PackageCommand[0] Package TeamViewer.TeamViewer 15.45.3 from Winget
info: WingetIntune.IntuneManager[1] Generating IntuneWin package for TeamViewer.TeamViewer 15.45.3 in C:\Tools\packages\
info: WingetIntune.IntuneManager[4] Downloading installer from https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe to C:\Users\stephan\AppData\Local\Temp\intunewin\TeamViewer.TeamViewer\15.45.3\TeamViewer_Setup_x64.exe
info: WingetIntune.Intune.ProcessIntunePackager[1] Creating Intune package from C:\Users\stephan\AppData\Local\Temp\intunewin\TeamViewer.TeamViewer\15.45.3 to C:\Tools\packages\TeamViewer.TeamViewer\15.45.3
info: WingetIntune.IntuneManager[6] Downloading logo from https://api.winstall.app/icons/TeamViewer.TeamViewer.png
info: WingetIntune.IntuneManager[0] Writing package readme for package TeamViewer.TeamViewer
```

It's running `winget show --id TeamViewer.TeamViewer --exact --accept-source-agreements --disable-interactivity` in the background, which gave a timeout.
