### ISSUE TITLE
intunwin not being created

### ISSUE THREAD

**Issue by Robbo58931** [svrooij/WingetIntune#22]
### Command

package

### Full command

winget-intune package DiskInternals.LinuxReader --package-folder C:\Tools\Packages

### App version

0.5.5+Branch.main.Sha.30b5f76fbaa043de94be29c4c05b692b19540b0e

### What happened?

Just started testing with this as it looks cool as hell - however i'm either missing something or the "intunewin" doesn't get created. I've tried differnet packages Adobe, 7-Zip, Linux Reader etc however there is no intunwin within the folder sturcture. There is no error messages when attempting the cmd. I can confirm the "intunwinapputil.exe" is located in Appdata\local\temp\intune. I can also see the .msi, .exe, .ps1 located for the apps within AppData\Local\Temp\intunewin\APPNAME. But when I look within the package folder all i see is the .json, detetion.txt and readme.txt, no intunwin
![image](https://github.com/svrooij/WingetIntune/assets/127307627/e817b182-8eb4-4a61-867a-f797b389b606)
![image](https://github.com/svrooij/WingetIntune/assets/127307627/385a1fb4-ad3b-4079-93fe-ae6e7c0931f9)
![image](https://github.com/svrooij/WingetIntune/assets/127307627/41eea678-5f1e-4539-a426-2bc75a1478eb)

### Command output

```Shell
C:\>winget-intune package DiskInternals.LinuxReader --package-folder C:\Tools\Packages
info: WingetIntune.Implementations.WingetManager[4] Getting package info for DiskInternals.LinuxReader (null)
info: WingetIntune.Commands.PackageCommand[0] Package DiskInternals.LinuxReader 4.18.1 from Winget
info: WingetIntune.IntuneManager[1] Generating IntuneWin package for DiskInternals.LinuxReader 4.18.1 in C:\Tools\Packages
info: WingetIntune.IntuneManager[4] Downloading installer from https://eu.diskinternals.com/download/Linux_Reader.exe to C:\Users\R_Robinson\AppData\Local\Temp\intunewin\DiskInternals.LinuxReader\4.18.1\Linux_Reader.exe
info: WingetIntune.Intune.ProcessIntunePackager[1] Creating Intune package from C:\Users\R_Robinson\AppData\Local\Temp\intunewin\DiskInternals.LinuxReader\4.18.1 to C:\Tools\Packages\DiskInternals.LinuxReader\4.18.1
info: WingetIntune.IntuneManager[6] Downloading logo from https://api.winstall.app/icons/DiskInternals.LinuxReader.png
info: WingetIntune.IntuneManager[0] Writing package readme for package DiskInternals.LinuxReader
```

### Windows version and current language

Windows11 Enterprise 23H2 (22631.2715)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@Robbo58931 thanks for flagging this issue, I'll have a look.

In the background I was already working on a new version that no longer has the dependency upon the content prep tool, but found an issue with it because of this message. Can you try to install the latest alpha version `0.6.0-alpha0013` and see if this fixes your issue?

```shell
dotnet tool upgrade --global SvRooij.Winget-Intune.Cli --version 0.6.0-alpha0013 --no-cache
```

**Comment by Robbo58931** [comment]
@svrooij sorry for the late response here. Just been testing again and all is working on the latest version. This is a fantastic bit of kit. Thank you! I will continue to test this week with a few apps and extra cmds.
