### ISSUE TITLE
[Bug]: Detection fails after installing

### ISSUE THREAD

**Issue by royklo** [svrooij/WingetIntune#23]
### Command

Publish

### Full command

winget-intune publish $PackageId --package-folder $Path --token $Token

### App version

0.6.0-alpha.13+Branch.dev.Sha.653373626c18735cd58d44b3a7506e83d30b68e3.653373626c18735cd58d44b3a7506e83d30b68e3

### What happened?

After packaging and publishing the apps (Notepad++ and Whatsapp Beta) for test purposes I noticed two different things. Both apps i made available via "available" assignment for all users to install it via company portal.

1. Noticed that notepad++ was installed, but detection failed.
2. Whatsapp Beta was installed as well (outdated?!), but detection failed as well.

So it seems like the detections doesn't work quiet well, but on top of that it's installing an outdated app as well? (could be package related ofcourse)

![image](https://github.com/svrooij/WingetIntune/assets/76492458/b7375f6b-eee0-4ea3-8bbf-354862fca2a7)

![image](https://github.com/svrooij/WingetIntune/assets/76492458/a480e7ae-59d7-4175-8ef1-b3b5957caa88)

### Windows version and current language

Windows 11 English 23h2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@royklo yes detection is bad... It uses a script which calls winget on the machine. If winget is not installed or really slow (which happens sometimes) it cannot detect the program.

For installing and outdated version `WhatsApp beta`. Here is my best guess, WhatsApp has an auto update mechanism. The version they uploaded to winget package index might be outdated. For apps that auto update, this app might not be the best solution.

**Comment by royklo** [comment]
The detection is based on [that script](https://github.com/svrooij/WingetIntune/blob/main/scripts/detection-with-version.ps1) what you're pointing to. That one fails. 

To be sure i've compared it with VS Code. only the variables on the first lines are different.

![image](https://github.com/svrooij/WingetIntune/assets/76492458/f329c0ab-6fc0-49eb-b50d-5ac14f5a14d0)

**Comment by svrooij** [comment]
I think there is something wrong with the detection, but I have no clue how to fix that.

https://twitter.com/svrooij/status/1737976673348284454?t=v5tFjq83efn8CTKgE_W0aQ&s=19

**Comment by svrooij** [comment]
@royklo Can you try installing [version 0.7.0-alpha0004](https://www.nuget.org/packages/SvRooij.Winget-Intune.Cli/0.7.0-alpha0004#readme-body-tab) and then retry?

I think that fixes your issue, and now also allows for uninstalling.
