### ISSUE TITLE
[Bug]: install file has no extension

### ISSUE THREAD

**Issue by vanooijen** [svrooij/WingetIntune#28]
### Command

install

### Full command

winget-intune.exe package Apple.iTunes --package-folder C:\Intune

### App version

0.7.0+Branch.main.Sha.6f15dab446ea9f234d069287d6ca0c3eadbc54be.6f15dab446ea9f234d069287d6ca0c3eadbc54be

### What happened?

First of all I'm very enthusiastic about this tool, so keep up the good work!

I tried this application with to install iTunes. After packaging and publishing it to Intune the installation failed.
When I extracted the intunewin file I noticed that the installer doesn't have an extension. I my case the installer was win64 instead of win64.exe. After changing the extension to .exe and repackage the files to an intunewin file the installation is working as expected. 
![intune](https://github.com/svrooij/WingetIntune/assets/113980956/2defe5c5-d35e-4134-b5a1-8fad72bbfede)
The download of the winget package is not working correctly with your tool. 
![intune-2](https://github.com/svrooij/WingetIntune/assets/113980956/41ce7ceb-5f05-4548-bb85-a74bbadc44ac)

### Windows version and current language

Windows 11 - EN

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Can you try with the latest alpha and see if that fixed your issue? https://www.nuget.org/packages/SvRooij.Winget-Intune.Cli/0.8.0-alpha0008

**Comment by vanooijen** [comment]
Hi Stephan,

The alpha version is working correctly. Good job!
