### ISSUE TITLE
[Bug]: Incorrect Install command displayed

### ISSUE THREAD

**Issue by FreshPrinceofBellR** [svrooij/WingetIntune#34]
### Command

package

### Full command

winget-intune package "Postman.Postman" --package-folder "C:\Windows\Temp\WingetIntune"

### App version

0.7.0+Branch.main.Sha.6f15dab446ea9f234d069287d6ca0c3eadbc54be.6f15dab446ea9f234d069287d6ca0c3eadbc54be

### What happened?

Hi,

Certain apps which don't publish the direct .exe or .msi file (example being Postman) and instead direct you to an installer URL seem to cause issues with the installer parametres.

Using Postman as an example:
Postman's Winget installer URL is: https://dl.pstmn.io/download/version/10.21.0/win64

Once going to this URL, it (at this moment in time) downloads a differently named file (not win64) called "Postman-win64-10.21.0-Setup.exe".

The packager doesn't list this in the readme.txt and seems to cause issues with installing the app in general.

### Windows version and current language

Windows 11 - English

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Yes some publishers do this (I hate that practice), this was however already discovered by someone else and is fixed in the latest alpha 0.8.0.0-alpha?? Check out the nuget page.

**Comment by FreshPrinceofBellR** [comment]
Brilliant, thanks for the quick response! It an awful practice, but happy to see someone reported it already!
