### ISSUE TITLE
[Bug]: Import-Module failed with error

### ISSUE THREAD

**Issue by emifo** [svrooij/WingetIntune#40]
### Command

package

### Full command

Import-Module WinTuner

### App version

WinTuner 0.8.1

### What happened?

Error when trying to import the WinTuner PS module (also tried on Windows Sandbox):

Import-Module : Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil.
At line:1 char:1
+ Import-Module -Name Wintuner -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

### Windows version and current language

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Did you try [installing](https://wintuner.app/docs/wintuner-powershell/installation#install-wintuner-powershell) it before trying to import?

**Comment by emifo** [comment]
My bad, I didn't run it in powershell core. 😮‍💨
