### ISSUE TITLE
[Bug]: CLI ...PS: 'winget-intune' is not recognized after install

### ISSUE THREAD

**Issue by AMKarl** [svrooij/WingetIntune#49]
### Command

install

### Full command

winget-intune package AgileBits.1Password --package-folder C:\WinGet\

### App version

Tool 'svrooij.winget-intune.cli' was reinstalled with the stable version (version '0.8.3').

### What happened?

1. Installed PowerShell - No issues
- Version 7.4.2.1 
2. Installed WinTuner - No issues
- Version 0.8.3+5223c56ae709364a27c44196b5873379a8bac500
3. installed Microsoft.DotNet.SDK.8 - No issues
- Version 8.0.204
4. Updated Nuget as a source
- Verified Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
5. Performed `dotnet tool install --global Svrooij.Winget-Intune.Cli`
- Received retune value Tool "'svrooij.winget-intune.cli' was installed with the stable version (version '0.8.3')."

PS C:\Windows\System32> winget-intune --version
winget-intune: The term 'winget-intune' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Command output

```Shell
PS C:\Windows\System32> winget-intune --version
winget-intune: The term 'winget-intune' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Windows version and current language

Windows 11 - English

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Try `wintuner .....`

Can you tell me where in the docs it still says `winget-intume` then I'll try to fix the docs as soon as possible.

**Comment by GetSetSan** [comment]
It's in "Package an installer", "Publish an installer", "Publish a store app", "Show Package Manifest", "MSI information".

**Comment by svrooij** [comment]
@GetSetSan and @AMKarl I did not update that part of the docs, oeps 🫣

![image](https://github.com/svrooij/WingetIntune/assets/1292510/6acc105f-865d-406c-8ac0-9681451a4eb4)

Update coming up

**Comment by GetSetSan** [comment]
Thanks @svrooij . Now there's a new error, using this command: wintuner publish ... --username "{user}@{domain}" it's throwing the below error: 
error code authentication_canceled microsoft.identity.client.msalclientexception

**Comment by svrooij** [comment]
@GetSetSan I'll add that to the docs as well.
