### ISSUE TITLE
[Bug]: CLI installation detection fails

### ISSUE THREAD

**Issue by eveslage** [svrooij/WingetIntune#55]
### Command

package

### Full command

wintuner package TeamViewer.TeamViewer --package-folder c:\...

### App version

0.8.4+d2bce5180d3b38c806e6139116c8eba1b5debcf1

### What happened?

after packaging, publishing and deploying a package, the installation detection script fails.

I looked into the PowerShell script and it looks like the output of running "winget" to detect the installation doesn't match.

in short: the detection script runs:

winget list --id TeamViewer.TeamViewer ...
-> running this locally on the target machine I get "No installed package found matching input criteria"

looking at the output of "winget list" I can see that a package with the ID "TeamViewer" is installed
so testing the detection script with packageID = TeamViewer instead of TeamViewer.TeamViewer, it works.

TeamViewer is only an example. I see other package ID with only a short version of the full package ID. 

### Windows version and current language

Windows 11 - Englisch, Windows 10 - Englisch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@eveslage it might be that they changed the output of winget?

the detection script template can be found here https://github.com/svrooij/WingetIntune/blob/d2bce5180d3b38c806e6139116c8eba1b5debcf1/src/WingetIntune/Intune/IntuneManagerConstants.cs#L52

want to give it a try to create a pull request?
Or do you maybe have the full output of the winget command?

**Comment by svrooij** [comment]
In the mean time I'm testing it myself.

![image](https://github.com/svrooij/WingetIntune/assets/1292510/b11b5991-d6bf-40cd-bdff-f3720f04fcd3)

![image](https://github.com/svrooij/WingetIntune/assets/1292510/ea7aa439-e3ae-4084-a27d-41bd6f23cfda)

I tested the command `winget list --id TeamViewer.TeamViewer --exact` which outputs the following:

```plain
PS C:\...> winget list --id TeamViewer.TeamViewer --exact
Name       Id                    Version Source
------------------------------------------------
TeamViewer TeamViewer.TeamViewer 15.53.6 winget
PS C:\...> winget --info
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3374
```

I'm tempted to close this issue with "works on my machine"
