### ISSUE TITLE
[Bug]: PowerShell does not authenticate

### ISSUE THREAD

**Issue by fergusstrachan** [svrooij/WingetIntune#69]
### CommandLet

Deploy-WtWin32App

### Full command

deploy-wtWin32App -overrideappname $AppName -Username $username -RootPackageFolder "d:\WinTuner" -PackageId Adobe.Acrobat.Reader.64-bit -Version 24.002.20759

### Module version

0.8.3

### What happened?

Fails!
I can't find reference to any of the error codes below, I'm afraid.

### Command output

```PowerShell
INFO: Loading package details from folder d:\WinTuner\Adobe.Acrobat.Reader.64-bit\24.002.20759
INFO: Uploading Win32App Acrobat 64-bit to Intune with file d:\WinTuner\Adobe.Acrobat.Reader.64-bit\24.002.20759\AcroRdrDCx642400220759_MUI.intunewin
INFO: [GraphAppUploader] Creating new Win32LobApp
Deploy-WtWin32App: Unknown Status: Unexpected
Context: Operation did not start in the allotted time.
Tag: 0x1e3d43d2 (error code 0) (internal error code 507331538)
Deploy-WtWin32App: Unknown Status: Unexpected
Context: Operation did not start in the allotted time.
Tag: 0x1e3d43d2 (error code 0) (internal error code 507331538)
```

### PowerShell version

7.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
Can you retry with the latest version? 0.8.6

**Comment by fergusstrachan** [comment]
Tried. Same issue.

I thought it was maybe something to do with deploying into Tenant1 when I'd previously worked on Tenant2 (so mismatch in the UPN and auth token), but it's working fine on 2 tenants, failing on 1.

Looks like it's specific to my tenant. Just wondering what these error codes mean and if they translate to anything I can look up.

**Comment by iamjustingraves** [comment]
Trying out wintuner and am seeing the same errors as OP. App packages just fine but fails to deploy with same error codes.

**Comment by svrooij** [comment]
Version 0.8.7 should fix your issue.

It has the option to `-NoBroker $true` to use browser authentication, and the authentication broker should also work again. Please re-open if the issue is not fixed.

**Comment by fergusstrachan** [comment]
Stephan,
Many thanks for this, and apologies for not responding for so long - I couldn't replicate the issue for some reason, so haven't been able to test the fixes you kindly provided.

I'll try again next week, but feel free to close this and we can always revisit if necessary.

F.
