### ISSUE TITLE
[Bug]: Unbale to use Client Credentials Authentication

### ISSUE THREAD

**Issue by atp0303** [svrooij/WingetIntune#74]
### CommandLet

Deploy-WtWin32App

### Full command

New-WtWingetPackage -PackageId "7zip.7zip" -PackageFolder "C:\temp\packages\" | Deploy-WtWin32App -ClientId XXX -ClientSecret XXX -TenantId XXX

### Module version

0.8.7

### What happened?

I'm trying to get Client Credentials Authorization working so i can enable a DevOps pipeline in Jenkins to automate the App installation and Updates daily.

I understand that this is not the recommended way but we plan to manage the secret key using Jenkins's credential manager so the key is not in plain sight.

I'm testing first directly on Windows 11 with PowerShell 7 but face the following error.

### Command output

```PowerShell
Use `Token`, `UseManagedIdentity`, `UseDefaultAzureCredential` or `Username` to select the graph connection type | (Parameter 'ParameterSetName')
```

### PowerShell version

7.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
I think you might be right. These credentials were added last and I did not test them.

They are built in but not in the validation step.

For now, you can set those values as environment variables.

- `AZURE_CLIENT_ID`
- `AZURE_CLIENT_SECRET`
- `AZURE_TENANT_ID`

And then use the `-UseDefaultCredentials` parameter.
In the default Azure credentials is the first credential provider, the environment credential, which loads it's details from the environment.

And now that I think of it. This might even be better because then the secrets don't need to be injected as parameters and you can just use them from the environment.

**Comment by atp0303** [comment]
Thanks.  Tried by faced another error:

![image](https://github.com/svrooij/WingetIntune/assets/1209692/a904a1f9-9047-4dbe-8ea8-26aabe1072d6)

`New-WtWingetPackage -PackageId "7zip.7zip" -PackageFolder "C:\temp\packages\" | Deploy-WtWin32App -UseDefaultCredentials`

`Line |
   8 |  … Folder "C:\temp\packages\" | Deploy-WtWin32App -UseDefaultCredentials
     |                                                   ~~~~~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'UseDefaultCredentials'.`

**Comment by svrooij** [comment]
Sorry I typed it wrong, check https://github.com/svrooij/WingetIntune/blob/83819fc329487afdaf76b11411bebcad20afe069/src/Svrooij.WinTuner.CmdLets/Commands/BaseIntuneCmdlet.cs#L39
For the exact spelling.

and here are the docs.
 https://wintuner.app/docs/wintuner-powershell/authentication#default-credentials

**Comment by atp0303** [comment]
I can get the upload working using interactive browser.  However still having trouble with Azure Credentials.
```
New-WtWingetPackage -PackageId "$($item)" -PackageFolder "$($packageFolder)" | Deploy-WtWin32App -UseDefaultAzureCredential $true
```

With the following error:

```
ClientSecretCredential authentication failed: AADSTS1002012: The provided value for scope 
| DeviceManagementConfiguration.ReadWrite.All is not valid. Client credential flows must have a scope value with 
| /.default suffixed to the resource identifier (application ID URI).
```

I read the MS documentation and it suggests we need to include in the scope: https://graph.microsoft.com/.default

Any pointers what to do?

**Comment by atp0303** [comment]
Hi @svrooij 

Thank you for the latest fix.  However i'm still having some trouble with v0.8.8

`foreach($item in $packages){
	New-WtWingetPackage -PackageId "$($item)" -PackageFolder "$($packageFolder)" | Deploy-WtWin32App -UseDefaultAzureCredential $true
}`

Results in the same error:
`ClientSecretCredential authentication failed: AADSTS1002012: The provided value for scope
     | DeviceManagementConfiguration.ReadWrite.All DeviceManagementApps.ReadWrite.All is not valid. Client credential
     | flows must have a scope value with /.default suffixed to the resource identifier`

**Comment by svrooij** [comment]
You can set the correct scope through the env `AZURE_SCOPES` or with the `-Scopes` parameter. And I would remove the `-UseDefault...` part that is no longer needed.

**Comment by atp0303** [comment]
Still facing an error im afraid:

Added the env AZURE_SCOPES

`$moduleName = "WinTuner"
$requiredVersion = "0.8.8"
$packageFolder = "C:\temp\packages\"

if(-not (Get-InstalledModule $moduleName -RequiredVersion $($requiredVersion))){
	Write-Host "Installing version $($requiredVersion)"	
	Install-Module -Name $moduleName -RequiredVersion $requiredVersion -Force				
	Import-Module $moduleName
}

#$packages = @(
#	"Microsoft.BingWallpaper"
#	"Notepad++.Notepad++"
#	"OpenVPNTechnologies.OpenVPNConnect"
#   "WinMerge.WinMerge"
#	"WinSCP.WinSCP"
#	"WiresharkFoundation.Wireshark"
#	"Git.Git"
#	"TortoiseGit.TortoiseGit" 
#	"Mozilla.Firefox"
#	"Google.Chrome"
#	"Postman.Postman"
#	"7zip.7zip"
#	"NGWIN.PicPick"
#	"DominikReichl.KeePass"
#)

$packages = @(
    "Postman.Postman"
)

foreach($item in $packages){
	New-WtWingetPackage -PackageId "$($item)" -PackageFolder "$($packageFolder)" | Deploy-WtWin32App -Scopes "https://graph.microsoft.com/.default"
}`

Results in error:
`Use `Token`, `UseManagedIdentity`, `UseDefaultAzureCredential` or `Username` to select the graph connection type
     | (Parameter 'ParameterSetName')`

Also tried using `New-WtWingetPackage -PackageId "$($item)" -PackageFolder "$($packageFolder)" | Deploy-WtWin32App -Scopes "https://graph.microsoft.com/.default"` with error:

`A parameter cannot be found that matches parameter name 'Scopes'.`

**Comment by svrooij** [comment]
You are not using the correct version, closing and locking this issue.

```powershell
PS C:\Users\StephanvanRooij> get-command -Module WinTuner

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Deploy-WtMsStoreApp                                0.8.8      WinTuner
Cmdlet          Deploy-WtWin32App                                  0.8.8      WinTuner
Cmdlet          Get-WtWin32Apps                                    0.8.8      WinTuner
Cmdlet          New-IntuneWinPackage                               0.8.8      WinTuner
Cmdlet          New-WtWingetPackage                                0.8.8      WinTuner
Cmdlet          Remove-WtWin32App                                  0.8.8      WinTuner
Cmdlet          Search-WtWinGetPackage                             0.8.8      WinTuner
Cmdlet          Unprotect-IntuneWinPackage                         0.8.8      WinTuner
Cmdlet          Update-WtIntuneApp                                 0.8.8      WinTuner

PS C:\Users\StephanvanRooij> get-help Deploy-WtWin32App -Full

NAME
    Deploy-WtWin32App

SYNOPSIS
    Create a Win32Lob app in Intune


SYNTAX
    Deploy-WtWin32App [-App] <Win32LobApp> [-IntuneWinFile] <String> [[-LogoPath] <String>] [[-UseManagedIdentity]
    <Boolean>] [[-Token] <String>] [[-Username] <String>] [[-TenantId] <String>] [[-ClientId] <String>]
    [-ProgressAction <ActionPreference>] [-ClientSecret <String>] [-UseDefaultAzureCredential <Boolean>] [-GraphId
    <String>] [-OverrideAppName <String>] [-NoBroker <Boolean>] [-Scopes <String[]>] [<CommonParameters>]

    Deploy-WtWin32App [-PackageFolder] <String> [[-UseManagedIdentity] <Boolean>] [[-Token] <String>] [[-Username]
    <String>] [[-TenantId] <String>] [[-ClientId] <String>] [-ProgressAction <ActionPreference>] [-ClientSecret
    <String>] [-UseDefaultAzureCredential <Boolean>] [-GraphId <String>] [-OverrideAppName <String>] [-NoBroker
    <Boolean>] [-Scopes <String[]>] [<CommonParameters>]

    Deploy-WtWin32App [-PackageId] <String> [-Version] <String> [-RootPackageFolder] <String> [[-UseManagedIdentity]
    <Boolean>] [[-Token] <String>] [[-Username] <String>] [[-TenantId] <String>] [[-ClientId] <String>]
    [-ProgressAction <ActionPreference>] [-ClientSecret <String>] [-UseDefaultAzureCredential <Boolean>] [-GraphId
    <String>] [-OverrideAppName <String>] [-NoBroker <Boolean>] [-Scopes <String[]>] [<CommonParameters>]


DESCRIPTION
    Use this command to upload an intunewin package to Microsoft Intune as a new Win32LobApp.

PARAMETERS
...
    -NoBroker <Boolean>
        Disable Windows authentication broker

        Required?                    false
        Position?                    named
        Default value                None
        Accept pipeline input?       False
        Accept wildcard characters?  false

    -Scopes <String[]>
        Specify the scopes to request, default is `DeviceManagementConfiguration.ReadWrite.All`,
        `DeviceManagementApps.ReadWrite.All`

        Required?                    false
        Position?                    named
        Default value                None
        Accept pipeline input?       False
        Accept wildcard characters?  false
```
