### ISSUE TITLE
[Bug]: PowerShell Some packages are configured with the wrong install parameters

### ISSUE THREAD

**Issue by mdurini-swisscom** [svrooij/WingetIntune#77]
### CommandLet

New-WtWingetPackage

### Full command

New-WtWingetPackage -PackageId "Microsoft.DotNet.Runtime.6" -PackageFolder "C:\temp\packages\" -Architecture "x64"

### Module version

0.8.8

### What happened?

Hi, first of all thank you for your amazing work. I've noticed that some winget packages are configured with the wrong install parameters. Some Examples:

1. Microsoft.VCRedist.2015+.x86
2. Microsoft.VCRedist.2015+.x64
3. Microsoft.VCRedist.2008.x64
4. Microsoft.DotNet.Runtime.6
5. VMware.HorizonClient

I've noticed that the json file contains only show "/norestart" for the key "installCommandLine", and the missing switch "/silent" is showed under "installers/installerSwitches/silent". this is causing an exe file running forever without any result. 

Thank you in advance.

### PowerShell version

7.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
So what you’re saying is that the switches in the `Silent` section are incomplete? Would you say it’s always a combination of `Custom` and `Silent`?

https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VCRedist/2015%2B/x64/14.38.33135.0/Microsoft.VCRedist.2015%2B.x64.installer.yaml

**Comment by svrooij** [comment]
https://github.com/svrooij/WingetIntune/discussions/83
