### ISSUE TITLE
[Bug]: PowerShell cmd does not allow filtering

### ISSUE THREAD

**Issue by andthenirealized** [svrooij/WingetIntune#80]
### CommandLet

Get-WtWin32Apps

### Full command

 Get-WtWin32Apps -user "user@domain.com" | Where-Object { $_.PackageId -like "Logitech.OptionsPlus"}

### Module version

0.8.8

### What happened?

All Win32 apps objects are output (13 different apps). This is not expected behavior. I would expect piped command only to output the object withe the parameter PackageId "Logitech.OptionsPlus"

### PowerShell version

7.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
https://github.com/svrooij/WingetIntune/discussions/83
