### ISSUE TITLE
[Bug]: PowerShell Auto-Update flag not checked

### ISSUE THREAD

**Issue by crcobb** [svrooij/WingetIntune#84]
### CommandLet

New-WtWingetPackage

### Full command

    Deploy-WtWin32App -Username $username -GraphId $($app.GraphId)

### Module version

0.8.9

### What happened?

App deploys properly but the Auto-Update flag isn't checked when superseding an older app version that has an "Available" deployment.  Debugging I see assignment.Settings isn't null so the code to set the flag is not called.  The graph SDK is a steep learning hill for me to climb so I didn't have any luck making changes in an attempt to fix.
```
if (assignment.Intent == GraphModels.InstallIntent.Available && assignment.Settings is null)
{
     assignment.Settings = new GraphModels.Win32LobAppAssignmentSettings { AutoUpdateSettings = new GraphModels.Win32LobAppAutoUpdateSettings { AutoUpdateSupersededApps = GraphModels.Win32LobAppAutoUpdateSupersededApps.Enabled } };
}
```

### PowerShell version

7.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@crcobb really appreciate the research!

You were right, they changed the graph api (Intune is still using the beta endpoints itself). They even removed the `Win32LobAppAutoUpdateSettings` from the client. Hold on tight, there is a fix coming.
