### ISSUE TITLE
[Bug]: Deploy-WtMsStoreApp returns "No products found for XP9KHM4BK9FZ7Q"

### ISSUE THREAD

**Issue by RobCannon** [svrooij/WingetIntune#85]
### CommandLet

other

### Full command

Deploy-WtMsStoreApp -PackageId $AppId -UserName $userName

### Module version

0.8.9

### What happened?

I used `winget search --source msstore Code` to get the msstore id for Visual Studio code.

I then run these command:
```
$AppId = "XP9KHM4BK9FZ7Q"   # Visual Studio Code
$inTunePackage = Deploy-WtMsStoreApp -PackageId $AppId -UserName $userName
```

I am hoping that this command will supply icons and other information for an MS Store package like it does for WinGet packages.

### Command output

```PowerShell
INFO: Uploading MSStore app XP9KHM4BK9FZ7Q to Intune
Deploy-WtMsStoreApp: [GraphStoreAppUploader] No products found for XP9KHM4BK9FZ7Q
Deploy-WtMsStoreApp: Object reference not set to an instance of an object.
```

### PowerShell version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@RobCannon can you tell me from which country you are? It might be that Visual Studio Code has a different ID in your country then in the country the library is checking against.

**Comment by RobCannon** [comment]
United States

**Comment by svrooij** [comment]
Will see what happens if I try here.

What happens if you use `-SearchQuery "Visual Studio Code"` instead of the id? It should use the first match.

**Comment by RobCannon** [comment]
It picks up the ID for Visual Studio Code Preview, but it returns the same error messages with a different ID.

**Comment by svrooij** [comment]
It was getting the images of a service that no longer exists..... Looking into an alternative solution

**Comment by svrooij** [comment]
@RobCannon no promise just yet, but.... https://x.com/svrooij/status/1815804527062442086

**Comment by svrooij** [comment]
Yes, I just built a new open-source project. If there is no api, we just have to create one https://proxy.wintuner.app/api/swagger/ui

**Comment by RobCannon** [comment]
Thank you!
