### ISSUE TITLE
[Bug]: PowerShell x86 only apps return No Installer Found Error

### ISSUE THREAD

**Issue by crcobb** [svrooij/WingetIntune#86]
### CommandLet

New-WtWingetPackage

### Full command

$package = New-WtWingetPackage -PackageId "Insecure.Nmap" -PackageFolder "c:\temp\wtpackage" -Verbose -Debug

### Module version

0.8.9

### What happened?

Received an error "No Installer Found".....  This appears it may be related to applications that only have x86 installers.  I ran into this issue with both the "Insecure.Nmap" and "WinSCP.WinSCP"

Looking the code for ComputeInstallerDetails I found that `packageOptions.Architecture` is set to `null`.  Looking at the code I was assuming this was fallback logic to look for x86 installers, which was less desirable.  I commented out the check for `packageOptions.Architecture == Architecture.X64` and I'm able to properly download and publish the application.  Not sure of the impact of this change so I didn't do a pull request.

```csharp
private void ComputeInstallerDetails(ref PackageInfo package, PackageOptions packageOptions)
    {
        var installer = package.GetBestFit(packageOptions.Architecture, packageOptions.InstallerContext, packageOptions.Locale)
            ?? package.GetBestFit(Architecture.Neutral, InstallerContext.Unknown, packageOptions.Locale)
            ?? package.GetBestFit(Architecture.Neutral, packageOptions.InstallerContext, packageOptions.Locale)
            ?? package.GetBestFit(packageOptions.Architecture, InstallerContext.Unknown, packageOptions.Locale);
        if (installer == null ) // && packageOptions.Architecture == Architecture.X64)
        {
            installer = package.GetBestFit(Architecture.X86, packageOptions.InstallerContext)
                ?? package.GetBestFit(Architecture.X86, InstallerContext.Unknown);
        }
        if (installer is null)
        {
            throw new ArgumentException($"No installer found for {package.PackageIdentifier} {package.Version} {packageOptions.Architecture}");
        }
```

### PowerShell version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@crcobb can you make a table the correct decisions We have `Architecture`, `InstallerContext` and `Language` to care about and then we want the most suitable installer `Msi -> Wix -> Other`

Apart from that you can specify a needed architecture [see](https://github.com/svrooij/WingetIntune/blob/main/src/Svrooij.WinTuner.CmdLets/Commands/NewWtWingetPackage.cs#L66L86) though this is not yet in the docs as I see 🤭

`-Architecture X86` that should allow you to package the app correctly.

**Comment by svrooij** [comment]
![image](https://github.com/user-attachments/assets/c744ff7c-64b0-4f6b-ba2e-ee336ec46222)
